<?php
/** @var $block \SectionBuilder\Product\Block\Adminhtml\AssignProducts */
?>

<?= /* @escapeNotVerified */ $block->getGridHtml() ?>
<?php $form = $block->getDataFormPart() ?>
<input type="hidden" name="product_list" data-form-part="<?= $form ?>" id="product_list" value=""  />
<script type="text/x-magento-init">
    {
        "*": {
            "SectionBuilder_Product/js/assign-products": {
                "selectedProducts": <?= /* @escapeNotVerified */ $block->getProductsJson() ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $block->getBlockGrid()->getJsObjectName() . '"' ?: '{}' ?>
            }
        }
    }
</script>
<script>
    require('mage/apply/main').apply();
</script>
